version: '3.2'
services:
    # Run local DB
    orn_service_api_mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "orn-order"
            MYSQL_USER: "orn-order_username"
            MYSQL_PASSWORD: "orn-order_password"
            MYSQL_ROOT_PASSWORD: "orn-order_password"
        ports:
        - '3306:3306'
        expose:
        - '3306'
        volumes:
        - ./mydb:/var/lib/mysql

    # Run local REDIS
    orn_service_cache:
        image: redis
        command: redis-server --requirepass root
        ports:
        - "6379:6379"
    # Run Service by development mode
    orn_service_api_golang:
        image: ralali/service:local
        build: .
        ports:
        - '3000:3000'
        command: air
        restart: on-failure
        depends_on:
        - orn_service_api_mysql
        volumes:
        - .:/app
