FROM golang:1.13-alpine AS builder

RUN mkdir -p /app
WORKDIR /app

COPY    . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o orn src/main.go

FROM alpine:3.7
RUN apk add tzdata \
    && export GIN_MODE=release
EXPOSE 3000
COPY --from=builder /app/ /opt/orn-id/
WORKDIR /opt/orn-id/
ENTRYPOINT ["/opt/orn-id/orn"]
ENTRYPOINT ["/opt/orn-id/orn", "-e", "production"]