definitions:
  rest.RestResponseData:
    properties:
      result:
        type: object
      status:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.RestResponseData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.RestResponseData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.RestResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.RestResponseData'
      summary: Check Health Status
      tags:
      - Health Status
  /v1/health/check:
    get:
      consumes:
      - application/json
      description: Check Health Status Detail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.RestResponseData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.RestResponseData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.RestResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.RestResponseData'
      summary: Check Health Status Detail
      tags:
      - HealthCheck Status
swagger: "2.0"
